### ISSUE TITLE
The issue regarding navigation permissions

### ISSUE THREAD

**Issue by tanphongtr** [unfoldadmin/django-unfold#230]
I'm encountering an issue with navigation permissions.
When I set the permission as ```'permission': lambda request: request.user.is_superuser```, the navigation displays when logged in with a superuser account.
However, when I log in with a non-superuser account, the navigation disappears as expected. Then, upon logging back in with the superuser account, the navigation does not appear.

![_](https://github.com/unfoldadmin/django-unfold/assets/11567406/5b0ad46b-7d0a-40eb-a96b-0dc02044e49c)

```
UNFOLD = {
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "Authentication and Authorization",
                "separator": True,  # Top border
                "items": [
                    {
                        "title": "Groups",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}
```

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #234

**Comment by Bokitza** [comment]
I removed the package and reinstalled it on current version 0.18.1, and this issue still happens. what am i missing?

@lukasvinclav 
<img width="851" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/58147254/9f82fc0a-acc9-4b0d-bd58-219a75c285a4">

**Comment by abdulsamadCS** [comment]
Having same issue in v0.19
@lukasvinclav
